### Word Embedding Techniques using Embedding Layer in Keras

In [3]:
#pip install tensorflow

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=["I am a good boy",
      "You are a good girl",
      "A for Apple",
      "I am a Data Scientist",
      "This NLP blog is so easy to understand",
      "Refer my other blogs too",
      "I had written blog on Machine Learning",
      "I had written blog on Data Preprocessing",
      "I had written blog on Statistics",
      "I had written blog on Deep Learning"]

In [6]:
sent

['I am a good boy',
 'You are a good girl',
 'A for Apple',
 'I am a Data Scientist',
 'This NLP blog is so easy to understand',
 'Refer my other blogs too',
 'I had written blog on Machine Learning',
 'I had written blog on Data Preprocessing',
 'I had written blog on Statistics',
 'I had written blog on Deep Learning']

In [7]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6875, 381, 3645, 2034, 7200], [1993, 4558, 3645, 2034, 2286], [3645, 5875, 1001], [6875, 381, 3645, 1799, 4542], [327, 6182, 3680, 4658, 5981, 8525, 675, 8230], [5533, 6974, 8791, 728, 3064], [6875, 62, 5489, 3680, 2105, 3230, 5236], [6875, 62, 5489, 3680, 2105, 1799, 1248], [6875, 62, 5489, 3680, 2105, 5378], [6875, 62, 5489, 3680, 2105, 836, 5236]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 6875  381 3645 2034 7200]
 [   0    0    0 1993 4558 3645 2034 2286]
 [   0    0    0    0    0 3645 5875 1001]
 [   0    0    0 6875  381 3645 1799 4542]
 [ 327 6182 3680 4658 5981 8525  675 8230]
 [   0    0    0 5533 6974 8791  728 3064]
 [   0 6875   62 5489 3680 2105 3230 5236]
 [   0 6875   62 5489 3680 2105 1799 1248]
 [   0    0 6875   62 5489 3680 2105 5378]
 [   0 6875   62 5489 3680 2105  836 5236]]


In [12]:
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 119ms/step
[[[ 4.62999195e-03 -2.42123753e-03  2.33042240e-03  4.96025123e-02
   -4.54834104e-02 -4.49165106e-02  1.15400665e-02  4.22747992e-02
   -1.70065761e-02  3.36885564e-02]
  [ 4.62999195e-03 -2.42123753e-03  2.33042240e-03  4.96025123e-02
   -4.54834104e-02 -4.49165106e-02  1.15400665e-02  4.22747992e-02
   -1.70065761e-02  3.36885564e-02]
  [ 4.62999195e-03 -2.42123753e-03  2.33042240e-03  4.96025123e-02
   -4.54834104e-02 -4.49165106e-02  1.15400665e-02  4.22747992e-02
   -1.70065761e-02  3.36885564e-02]
  [-4.38719057e-02 -3.56303938e-02 -1.45795718e-02 -2.53742468e-02
    3.94769423e-02 -2.41149794e-02 -2.29990967e-02 -1.74435377e-02
    5.03488630e-03 -5.23948669e-03]
  [ 2.94452906e-03 -1.82253830e-02 -4.78469245e-02  6.46306202e-03
   -2.39467267e-02  2.49389298e-02  4.91186269e-02  2.87089460e-02
    1.42068975e-02 -4.56177369e-02]
  [ 1.99398659e-02  8.99872929e-03 -1.00243576e-02 -4.81173508e-02
    1.07954256e-02  1.77051313

In [16]:
embedded_docs[0]

array([   0,    0,    0, 6875,  381, 3645, 2034, 7200])

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 41ms/step
[[ 0.00462999 -0.00242124  0.00233042  0.04960251 -0.04548341 -0.04491651
   0.01154007  0.0422748  -0.01700658  0.03368856]
 [ 0.00462999 -0.00242124  0.00233042  0.04960251 -0.04548341 -0.04491651
   0.01154007  0.0422748  -0.01700658  0.03368856]
 [ 0.00462999 -0.00242124  0.00233042  0.04960251 -0.04548341 -0.04491651
   0.01154007  0.0422748  -0.01700658  0.03368856]
 [-0.04387191 -0.03563039 -0.01457957 -0.02537425  0.03947694 -0.02411498
  -0.0229991  -0.01744354  0.00503489 -0.00523949]
 [ 0.00294453 -0.01822538 -0.04784692  0.00646306 -0.02394673  0.02493893
   0.04911863  0.02870895  0.0142069  -0.04561774]
 [ 0.01993987  0.00899873 -0.01002436 -0.04811735  0.01079543  0.01770513
  -0.03055502  0.03293211  0.03688853 -0.01669665]
 [ 0.01422809  0.002185    0.03921251  0.01024468 -0.04461597  0.0236478
  -0.01644752 -0.01168774 -0.04884813 -0.0450046 ]
 [-0.02853187  0.01028491 -0.0240731   0.01282595 -0.01442986  0.02615631
